apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-service-postgres-pvc
  namespace: payment-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "800Mi"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-db
  namespace: payment-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-db
  template:
    metadata:
      labels:
        app: auth-service-db
    spec:
      containers:
        - name: postgres
          image: postgres:18-alpine

          resources:
            requests:
              memory: "512Mi"
              cpu: "300m"
            limits:
              memory: "800Mi"
              cpu: "1"

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: payment-system-secrets
                  key: AUTH_SERVICE_DB_NAME

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: payment-system-secrets
                  key: AUTH_SERVICE_DB_USERNAME

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-system-secrets
                  key: AUTH_SERVICE_DB_PASSWORD

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: auth-service-postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-db
  namespace: payment-system
spec:
  type: ClusterIP
  selector:
    app: auth-service-db
  ports:
    - port: 5432
      targetPort: 5432