apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-mongodb-pvc
  namespace: payment-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "800Mi"
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-payment-mongodb
  namespace: payment-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service-payment-mongodb
  template:
    metadata:
      labels:
        app: payment-service-payment-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:8.0

          resources:
            requests:
              memory: "512Mi"
              cpu: "300m"
            limits:
              memory: "800Mi"
              cpu: "1"

          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: payment-system-secrets
                  key: PAYMENT_SERVICE_MONGO_DB_NAME

            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: payment-system-secrets
                  key: PAYMENT_SERVICE_MONGO_DB_USERNAME

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-system-secrets
                  key: PAYMENT_SERVICE_MONGO_DB_PASSWORD

          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db

          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
            
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: payment-mongodb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service-payment-mongodb
  namespace: payment-system
spec:
  type: ClusterIP
  selector:
    app: payment-service-payment-mongodb
  ports:
    - port: 27017
      targetPort: 27017