server:
  port: ${AUTH_SERVICE_PORT}

spring:
  config:
    activate:
      on-profile: docker

  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_SECRET_PASSWORD}

  datasource:
    url: jdbc:postgresql://${AUTH_SERVICE_DB_HOST}:${AUTH_SERVICE_DB_PORT}/${AUTH_SERVICE_DB_NAME}
    username: ${AUTH_SERVICE_DB_USERNAME}
    password: ${AUTH_SERVICE_DB_PASSWORD}

  kafka:
    producer:
      properties:
        max.block.ms: 5000
        delivery.timeout.ms: 14000
        request.timeout.ms: 7000

logging:
  level:
    root: INFO
