server:
  port: ${AUTH_SERVICE_PORT}

spring:
  config:
    activate:
      on-profile: local

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_SECRET_PASSWORD}

  datasource:
    url: jdbc:postgresql://localhost:${AUTH_SERVICE_DB_PORT}/${AUTH_SERVICE_DB_NAME:auth_db}
    username: ${AUTH_SERVICE_DB_USERNAME:db_username}
    password: ${AUTH_SERVICE_DB_PASSWORD:db_password}

  kafka:
    producer:
      properties:
        max.block.ms: 5000
        delivery.timeout.ms: 14000
        request.timeout.ms: 7000

logging:
  level:
    root: INFO
