spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: none
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    enabled: true

  jwt:
    secret: ${PRIVATE_KEY}
    access-expiration: ${JWT_ACCESS_EXPIRATION}
    refresh-expiration: ${JWT_PRIVATE_EXPIRATION}
    max-session-count: 5
    prod: ${JWT_IS_PROD:true}

  kafka:
    bootstrap-servers: ${KAFKA_HOST_PORT}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
    consumer:
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      max-poll-records: 100
    listener:
      type: batch
      concurrency: 4
      ack-mode: manual_immediate
      immediate-stop: true

  config:
    import: optional:file:.env-local[.properties]

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

  endpoints:
    web:
      exposure:
        include: health,info

app:
  no-security: true
